import { useStore, getLevel, BADGES } from '../store'

function copyToClipboard(text) {
  navigator.clipboard?.writeText(text).catch(() => {})
}

export default function ParentDashboard({ onBack }) {
  const { store, update } = useStore()
  const {
    name, xp, streak, totalQuizzes, totalCorrect, totalAttempted,
    badges, sessionHistory, wrongLog, roundStats, flashcardsLearned,
  } = store

  const level = getLevel(xp)
  const accuracy = totalAttempted > 0 ? Math.round((totalCorrect / totalAttempted) * 100) : 0

  const roundNames = { 1: 'Common Errors', 2: 'Scrambled Words', 3: 'Correct Spelling', 4: 'Spell The Word' }
  const roundEmojis = { 1: '🔍', 2: '🔀', 3: '✏️', 4: '🗣️' }

  const weakRound = Object.entries(roundStats)
    .filter(([, s]) => s.total > 0)
    .sort(([, a], [, b]) => (a.correct / a.total) - (b.correct / b.total))[0]

  const bestRound = Object.entries(roundStats)
    .filter(([, s]) => s.total > 0)
    .sort(([, a], [, b]) => (b.correct / b.total) - (a.correct / a.total))[0]

  const allWrong = Object.entries(wrongLog)
    .flatMap(([rn, entries]) => entries.map(e => ({ ...e, roundN: rn })))
    .sort((a, b) => b.count - a.count)
    .slice(0, 10)

  const generateReport = () => {
    const lines = [
      `📊 ${name}'s Spelling Progress Report`,
      `Date: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      ``,
      `🏅 Level: ${level.n} — ${level.title}`,
      `⭐ XP: ${xp} | 🔥 Streak: ${streak.count} days`,
      `📝 Quizzes: ${totalQuizzes} | ✅ Overall accuracy: ${accuracy}%`,
      ``,
      `Round Performance:`,
      ...Object.entries(roundStats).map(([n, s]) =>
        `  ${roundEmojis[n]} Round ${n} (${roundNames[n]}): ${s.total > 0 ? Math.round((s.correct/s.total)*100) : 0}% (${s.correct}/${s.total})`
      ),
      ``,
      `📖 Word Basket: ${flashcardsLearned.length}/100 words learned`,
      `🏅 Badges: ${badges.length}/${BADGES.length} earned`,
      ``,
      weakRound ? `⚠️ Needs most practice: Round ${weakRound[0]} (${roundNames[weakRound[0]]})` : '',
      allWrong.length > 0 ? `\nTop missed questions:` : '',
      ...allWrong.slice(0, 5).map(w => `  • ${w.label} (Round ${w.roundN}, missed ${w.count}x)`),
      ``,
      `Generated by Ira's Spell Lab 🌟`,
    ]
    copyToClipboard(lines.filter(l => l !== undefined).join('\n'))
    alert('Progress report copied to clipboard! Paste it in WhatsApp or email. 📋')
  }

  const resetData = () => {
    if (confirm('Reset ALL progress? This cannot be undone.')) {
      update({ xp: 0, streak: { count: 0, lastDate: null }, totalQuizzes: 0, totalCorrect: 0, totalAttempted: 0, badges: [], sessionHistory: [], wrongLog: { 1: [], 2: [], 3: [], 4: [] }, roundStats: { 1: {correct:0,total:0}, 2:{correct:0,total:0}, 3:{correct:0,total:0}, 4:{correct:0,total:0} }, flashcardsLearned: [] })
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <div className="bg-white/10 backdrop-blur-sm border-b border-white/20 px-4 py-3 flex items-center gap-3">
        <button onClick={onBack} className="text-white p-1 hover:text-white/80 transition">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7"/>
          </svg>
        </button>
        <h2 className="font-display text-2xl text-white flex-1">👨‍👩‍👧 Parent Dashboard</h2>
      </div>

      <div className="flex-1 overflow-y-auto px-4 py-4 max-w-lg mx-auto w-full space-y-4">

        {/* Overview */}
        <div className="bg-white rounded-3xl p-5 shadow-xl">
          <h3 className="font-bold text-gray-500 text-xs uppercase tracking-wider mb-3">Overview — {name}</h3>
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Level', value: `${level.n} — ${level.title}`, icon: level.emoji },
              { label: 'Total XP', value: `${xp} XP`, icon: '⭐' },
              { label: 'Practice Streak', value: `${streak.count} day${streak.count !== 1 ? 's' : ''}`, icon: '🔥' },
              { label: 'Accuracy', value: `${accuracy}%`, icon: '🎯' },
              { label: 'Quizzes Done', value: totalQuizzes, icon: '📝' },
              { label: 'Words Learned', value: `${flashcardsLearned.length}/100`, icon: '📖' },
            ].map(s => (
              <div key={s.label} className="bg-gray-50 rounded-2xl p-3">
                <div className="text-xl mb-1">{s.icon}</div>
                <div className="font-bold text-gray-800">{s.value}</div>
                <div className="text-gray-400 text-xs">{s.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Round performance */}
        <div className="bg-white rounded-3xl p-5 shadow-xl">
          <h3 className="font-bold text-gray-500 text-xs uppercase tracking-wider mb-4">Round Performance</h3>
          {Object.entries(roundStats).map(([n, s]) => {
            const pct = s.total > 0 ? Math.round((s.correct / s.total) * 100) : 0
            const barColor = pct >= 80 ? 'bg-emerald-400' : pct >= 60 ? 'bg-yellow-400' : pct > 0 ? 'bg-red-400' : 'bg-gray-200'
            const label = pct >= 80 ? 'Strong 💪' : pct >= 60 ? 'Good 👍' : pct > 0 ? 'Needs practice 📚' : 'Not practised yet'
            return (
              <div key={n} className="mb-4">
                <div className="flex items-center justify-between mb-1">
                  <span className="font-bold text-gray-700 text-sm">{roundEmojis[n]} Round {n}: {roundNames[n]}</span>
                  <span className="font-bold text-gray-800 text-sm">{s.total > 0 ? `${pct}%` : '—'}</span>
                </div>
                <div className="bg-gray-100 rounded-full h-4 overflow-hidden mb-0.5">
                  <div className={`${barColor} h-4 rounded-full transition-all duration-700`} style={{ width: `${pct}%` }} />
                </div>
                <div className="text-xs text-gray-400">{s.correct}/{s.total} correct · {label}</div>
              </div>
            )
          })}
          {weakRound && (
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-3 mt-2">
              <p className="text-amber-800 text-sm font-bold">
                💡 Focus area: <span className="text-amber-900">{roundNames[weakRound[0]]}</span> needs the most practice.
                Try Round {weakRound[0]} in Practice mode for targeted improvement.
              </p>
            </div>
          )}
          {bestRound && (
            <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3 mt-2">
              <p className="text-emerald-800 text-sm font-bold">
                🌟 Strongest: <span className="text-emerald-900">{roundNames[bestRound[0]]}</span> — keep it up!
              </p>
            </div>
          )}
        </div>

        {/* Wrong answers / weak spots */}
        {allWrong.length > 0 && (
          <div className="bg-white rounded-3xl p-5 shadow-xl">
            <h3 className="font-bold text-gray-500 text-xs uppercase tracking-wider mb-3">Top Missed Questions</h3>
            <p className="text-gray-500 text-xs mb-3">These were answered incorrectly most often across all sessions:</p>
            <div className="space-y-2">
              {allWrong.map((w, i) => (
                <div key={i} className="flex items-center gap-3 bg-red-50 rounded-xl px-3 py-2">
                  <span className="text-red-400 font-bold text-sm w-5">{i + 1}.</span>
                  <span className="font-bold text-gray-700 text-sm flex-1 truncate">{w.label}</span>
                  <span className="text-xs text-gray-400 flex-shrink-0">Round {w.roundN}</span>
                  <span className="bg-red-200 text-red-700 text-xs font-bold px-2 py-0.5 rounded-full flex-shrink-0">
                    ×{w.count}
                  </span>
                </div>
              ))}
            </div>
            <p className="text-gray-400 text-xs mt-3">💡 Use "Practice Weak Spots" mode to focus on these.</p>
          </div>
        )}

        {/* Session history */}
        {sessionHistory.length > 0 && (
          <div className="bg-white rounded-3xl p-5 shadow-xl">
            <h3 className="font-bold text-gray-500 text-xs uppercase tracking-wider mb-3">Session History</h3>
            <div className="space-y-2">
              {[...sessionHistory].reverse().slice(0, 10).map((s, i) => {
                const pct = s.total > 0 ? Math.round((s.score / s.total) * 100) : 0
                const d = new Date(s.date)
                const dateStr = d.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })
                return (
                  <div key={i} className="flex items-center gap-3 bg-gray-50 rounded-xl px-3 py-2.5">
                    <div className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center font-bold text-purple-600 text-xs flex-shrink-0">
                      {s.score}/{s.total}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-bold text-gray-700 text-sm">{dateStr}</div>
                      <div className="text-gray-400 text-xs">{pct}% · ~{s.duration || '—'} min · Rounds: {s.rounds?.join(', ') || '—'}</div>
                    </div>
                    <div className={`text-sm font-bold ${pct >= 80 ? 'text-emerald-500' : pct >= 60 ? 'text-yellow-500' : 'text-red-400'}`}>
                      {pct >= 80 ? '🌟' : pct >= 60 ? '👍' : '📚'}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Badges summary */}
        <div className="bg-white rounded-3xl p-5 shadow-xl">
          <h3 className="font-bold text-gray-500 text-xs uppercase tracking-wider mb-3">
            Badges Earned ({badges.length}/{BADGES.length})
          </h3>
          <div className="flex flex-wrap gap-2">
            {BADGES.map(b => (
              <div
                key={b.id}
                title={b.name + ': ' + b.desc}
                className={`text-2xl p-2 rounded-xl ${badges.includes(b.id) ? 'bg-yellow-100' : 'bg-gray-100 grayscale opacity-30'}`}
              >
                {badges.includes(b.id) ? b.icon : '🔒'}
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="space-y-3 pb-6">
          <button
            onClick={generateReport}
            className="w-full py-4 bg-gradient-to-r from-emerald-400 to-green-500 text-white font-bold rounded-2xl shadow-lg hover:shadow-xl transition hover:scale-105 active:scale-95"
          >
            📤 Copy Progress Report (for WhatsApp/Email)
          </button>
          <button
            onClick={resetData}
            className="w-full py-3 bg-red-50 text-red-500 font-bold rounded-2xl border border-red-200 hover:bg-red-100 transition text-sm"
          >
            🔄 Reset All Progress
          </button>
        </div>
      </div>
    </div>
  )
}
